network_specs:
  hidden_dims: [512, 512, 512, 512, 512, 512, 512, 512]
  dropout: 0.2
  weight_norm: True

latent_dim: 256
latent_vec_bound: 1.0
latent_insert: 4
latent_vec_regularization: True
latent_vec_reg_lambda: 0.0001

sdf_clamping_dist: 0.1

# Training parameters
epochs: 2000
batch_size: 64
batch_split: 8
save_freq: 500
samples_per_scene: 8000
network_lr_schedule:
  start: 0.0005
  decay: 0.5
  interval: 500
latent_vec_lr_schedule:
  start: 0.001
  decay: 0.5
  interval: 500

# Reconstruction parameters
reconstruct_epochs: 800
reconstruct_lr_schedule:
  start: 0.0005
  decay: 0.1
  interval: 400

# Sampling / Data parameters
n_samples: 50000
data_dir: "data/sdf/03797390"
shapenet_dir: "data/shapenet/03797390"
train_test_split: "config/03797390/split.json"
