network_specs:
  hidden_dims: [512, 512, 512, 512, 512, 512, 512, 512]
  dropout: 0.2
  weight_norm: True

latent_dim: 256
latent_vec_bound: 1.0
latent_insert: 4

network_lr_schedule:
  start: 0.0005
  decay: 0.5
  interval: 500

latent_vec_lr_schedule:
  start: 0.001
  decay: 0.5
  interval: 500

epochs: 2000
save_freq: 500
