network_specs:
  hidden_dims: [512, 512, 512, 512, 512, 512, 512, 512]
  dropout: 0.2
  weight_norm: True

latent_dim: 256
latent_vec_bound: 1.0
latent_insert: 4
latent_vec_regularization: True
latent_vec_reg_lambda: 0.0001

network_lr_schedule:
  start: 0.0005
  decay: 0.5
  interval: 500

latent_vec_lr_schedule:
  start: 0.001
  decay: 0.5
  interval: 500

sdf_clamping_dist: 0.1

epochs: 2000
batch_size: 64
batch_split: 8
save_freq: 500

data_dir: "data/sdf/03797390"
train_test_split: "config/03797390/split.json"
